### ISSUE TITLE
Dependency hell with SignalR

### ISSUE THREAD

**Issue by mixxit** [nickgamb/Okta_Unity#2]
Microsoft.AspNetCore.SignalR.Client needs System.Memory 4.5.4 which requires System.Runtime.CompilerServices.Unsafe.dll 4.7.1 

However unity is complaining that okta needs System.Runtime.CompilerServices.Unsafe.dll 5.0.0 

Is there a way to build this independently with a lower version?

**Comment by nickgamb** [comment]
The Okta .NET SDK is open source. https://github.com/okta/okta-sdk-dotnet if you are asking to compile it yourself?

**Comment by mixxit** [comment]
brilliant thank you! :-)
